### ISSUE TITLE
A PHP Error was encountered.

### ISSUE THREAD

**Issue by MikeVIP** [ivantcholakov/codeigniter-phpmailer#17]
After the update to version 1.2.7 displays warning:
`Message: Declaration of MY_Email::initialize($config = Array) should be compatible with CI_Email::initialize(array $config = Array)`
`Filename: libraries/MY_Email.php`
`Line Number: 0`
`Backtrace:`
`File: /srv/http/.../application/libraries/Aauth.php`
`Line: 112`
`Function: library `
`File: /srv/http/.../index.php`
`Line: 315`
`Function: require_once`

I have:
PHP Version: 7.0.9
CodeIgniter 3.1.0
Codeigniter-phpmailer: 1.2.7

**Comment by ivantcholakov** [comment]
Strange, I have added an error handler for dealing with this warning and it works for me, PHP 7.0.8.

**Comment by ivantcholakov** [comment]
@MikeVIP

See this change: https://github.com/ivantcholakov/codeigniter-phpmailer/commit/88bcc768cdbff5570baccdcc7e0967b5872e7149

Does it fix the warning? I doubt about that, but let me see.

**Comment by MikeVIP** [comment]
Thank you very much for your answer, unfortunately, the problem persists.

Already yesterday I tried to change of function: `_email_library_error_handler`, before I wrote about this warning.

**Comment by ivantcholakov** [comment]
@MikeVIP

How about this? https://github.com/ivantcholakov/codeigniter-phpmailer/commit/533eac924a94b13eaf4704a9806c6dce7b1b3e7a

**Comment by MikeVIP** [comment]
Version: 1.2.8, works fine!
Thank you!

**Comment by ivantcholakov** [comment]
Thank you.
