### ISSUE TITLE
Unable to load the requested file: helpers/my_email_helper.php

### ISSUE THREAD

**Issue by salimbenfarhat** [ivantcholakov/codeigniter-phpmailer#19]
Hi. Ive a problem to install PHPMailer with Codeigniter 3.
Ive put all the file correctly on the application folder. 
Ive configured the email setting. But when I Go on the browser, I get this "Unable to load the requested file: helpers/my_email_helper.php". Help, please.

**Comment by ivantcholakov** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/3.1.0/application/config/config.php#L117 - check this setting. I wonder why my_email_helper.php file is searched instead of MY_email_helper.php .

**Comment by ivantcholakov** [comment]
@salimbenfarhat
What happened? Is there a problem here?
