### ISSUE TITLE
Return Path

### ISSUE THREAD

**Issue by gelinger777** [ivantcholakov/codeigniter-phpmailer#23]
Dear Ivan, as you maybe know, its not possible to set Return-path header on SMTP protocol in email class of codeigniter.  Do you think it would be possible to do when we replace it with your lib? Syntax will be the same? 

$this->email->reply_to("xyz@yahoo.com","Sender Name","returnpath@email.com"); 

????

**Comment by ivantcholakov** [comment]
I don't test the original CodeIgniter library, in my products I rely on this PHPMailer-based library only. I cannot make a comparison to confirm your observations.

What I can see is that your example is wrong, the method reply_to() has no third parameter. See instead
```php
public function from($from, $name = '', $return_path = NULL)
```

**Comment by gelinger777** [comment]
Yes, absolutely right! I wanted to try to send something but I am strangely getting

Error
Message: The file PHPMailerAutoload.php can not be found.

But the file is there. Any ideas what can be the problem?

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-phpmailer/blob/v1.2.13/libraries/MY_Email_3_1_x.php#L603

Before this lime place temporarily the following line:

```php
echo APPPATH.'third_party/phpmailer/PHPMailerAutoload.php'; exit;
```

Make a test, see what path it outputs and whether there is a file on this path. Then remove the temporary line.
