### ISSUE TITLE
Error in Library MY_Email_3_0_x.php

### ISSUE THREAD

**Issue by dhaivat28** [ivantcholakov/codeigniter-phpmailer#25]
When i run the controller which has your test code, It sends the mail and is working perfectly fine but the controller gives me this error. Can you please have a look ?

Severity: Warning

Message: Declaration of MY_Email::set_alt_message($str) should be compatible with CI_Email::set_alt_message($str = '')

Filename: libraries/MY_Email_3_0_x.php

Line Number: 0

Codeigniter Version: 2.2.6
PHP Version: 7.0

**Comment by ivantcholakov** [comment]
@dhaivat28 

Could you test the last commit I've made?

**Comment by dhaivat28** [comment]
sure. Ill just test it!

**Comment by dhaivat28** [comment]
It's Working! Thank your for the update. Cheers :+1:

**Comment by ivantcholakov** [comment]
Thank you.
