### ISSUE TITLE
SMTP connect() failed

### ISSUE THREAD

**Issue by johnjake** [ivantcholakov/codeigniter-phpmailer#30]
Hey good day thank you for the awesome library integration to CI but i receive this error, when sending email. 

bool(false) 
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by ivantcholakov** [comment]
Change temporarily the following configuration setting this way:

```php
$config['smtp_debug']       = 4;
```

Thus you will get a more detailed error message with a clue what the cause might be. Most probably you have no permission to connect to the email server.
