### ISSUE TITLE
Message: fwrite(): send error

### ISSUE THREAD

**Issue by myrain25** [ivantcholakov/codeigniter-phpmailer#34]
i got an error like this when send email, Message: fwrite(): send of 9 bytes failed with errno=32 Broken pipe

**Comment by ivantcholakov** [comment]
It is too little information you are giving to me. Probably it is an authentication problem.

Here something similar has been reported:
https://stackoverflow.com/questions/38341933/unable-to-send-emails-smpt-errors-in-codigniter-3
