### ISSUE TITLE
mail->attach() doesnt work for me

### ISSUE THREAD

**Issue by mayo83** [ivantcholakov/codeigniter-phpmailer#35]
Hey,

i like the repo a lot but i have a problem with attaching files to my email. 

        $this->email
                ->from(email_sender)
                ->to(email_receiver)
                ->subject(email_subject)
                ->message(email_body)
                ->attach($_SERVER["DOCUMENT_ROOT"]."somefolder/".$attachments);

I checked if the path is wrong, but i cant find my error here. Some advice would be realy cool.

**Comment by ivantcholakov** [comment]
Try something easy first:
```php
->attach(FCPATH.'favicon.ico')
```
Then try something hardcoded within a subdirectory:
```php
->attach(FCPATH.'somefolder/'.'myfile.png')
```
Then introduce your variable.

**Comment by mayo83** [comment]
With FCPATH i could attach my Files. Didnt investigate why it did not worked with the $_SERVER["DOCUMENT_ROOT"]. Thx for the reply. 👍
