### ISSUE TITLE
First link under Readings doesn't work

### ISSUE THREAD

**Issue by harishkotra** [ivantcholakov/codeigniter-phpmailer#36]
The first link listed under Readings doesn't work anymore. Looks like the domain expired.

> http://bisakomputer.com/membuat-pengiriman-email-terjadwal-dengan-framework-codeigniter/ - "Membuat Pengiriman Email Terjadwal dengan Framework CodeIgniter" by Arif Rachman, in Indonesian language.

**Comment by ivantcholakov** [comment]
Thank you.
