### ISSUE TITLE
How to embed image in body?

### ISSUE THREAD

**Issue by webmazz** [ivantcholakov/codeigniter-phpmailer#38]
Hi,
how can I embed image in body?

**Comment by defro** [comment]
Hello @webmazz 

You can do it by using PhpMailer instance like this : https://gist.github.com/arzola/0418a9f059a0fa45e425

Regards,
Joël

**Comment by webmazz** [comment]
> Hello @webmazz
> 
> You can do it by using PhpMailer instance like this : https://gist.github.com/arzola/0418a9f059a0fa45e425
> 
> Regards,
> Joël


@defro , thanks for reply!

When I try use  AddEmbeddedImage method from example I have this error: 
> Message: Call to undefined method MY_Email::AddEmbeddedImage()

**Comment by defro** [comment]
According to example on [README](https://github.com/ivantcholakov/codeigniter-phpmailer/blob/master/README.md), did you write: `$this->email->AddEmbeddedImage("rocks.png", "my-attach", "rocks.png")` ?

**Comment by defro** [comment]
Hello @webmazz 
Did you solve your problem ? If yes, can you close this issue ?

**Comment by webmazz** [comment]
@defro, I try something like this:
```
$result = $this->email
    ->from('maazi1@maazi1.unixstorm.org')
    ->to($data_user['email'])
    ->subject($subject)
    ->message($message)
    ->AddEmbeddedImage(base_url('assets/dist/images/logo.svg'), 'logo', 'logo.svg')
    ->send();
```
and I have this error:

> Message: Call to undefined method MY_Email::AddEmbeddedImage()

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.3.43/platform/common/modules/email/controllers/Test_controller.php

https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.3.43/platform/common/modules/email/controllers/Email_controller.php

Here is an example on how I embed a logo withim a message. I don't use the library directly, but anyway, you may figure out how to adapt your code. Use the method attach() and pay attention that it has a parameter added by me - $embedded_image. Set it to true, if it is necessary.

**Comment by webmazz** [comment]
@ivantcholakov , thanks for reply.

I try use your method attach() and I have code like this:
```
$result = $this->email
    ->from('email@email.com')
    ->to($data_user['email'])
    ->subject($subject)
    ->message($message)
    ->attach(base_url('assets/dist/images/logo.svg'), true)
    ->send();
```
and this doesn't work. Image isn't attach.

**Comment by ivantcholakov** [comment]
Show me what $message contains.

**Comment by ivantcholakov** [comment]
I've updated README.md with the following tested example:
```php
$this->load->library('email');

$subject = 'This is a test';
$message = '
    <p>This message has been sent for testing purposes.</p>

    <!-- Attaching an image example - an inline logo. -->
    <p><img src="cid:logo_src" /></p>
';

// Get full html:
$body = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=' . strtolower(config_item('charset')) . '" />
    <title>' . html_escape($subject) . '</title>
    <style type="text/css">
        body {
            font-family: Arial, Verdana, Helvetica, sans-serif;
            font-size: 16px;
        }
    </style>
</head>
<body>
' . $message . '
</body>
</html>';
// Also, for getting full html you may use the following internal method:
//$body = $this->email->full_html($subject, $message);

// Attaching the logo first.
$file_logo = FCPATH.'apple-touch-icon-precomposed.png';  // Change the path accordingly.
// The last additional parameter is set to true in order
// the image (logo) to appear inline, within the message text:
$this->email->attach($file_logo, 'inline', null, '', true);
$cid_logo = $this->email->get_attachment_cid($file_logo);
$body = str_replace('cid:logo_src', 'cid:'.$cid_logo, $body);
// End attaching the logo.

$result = $this->email
    ->from('yourusername@gmail.com')
    ->reply_to('yoursecondemail@somedomain.com')    // Optional, an account where a human being reads.
    ->to('therecipient@otherdomain.com')
    ->subject($subject)
    ->message($body)
    ->send();

var_dump($result);
echo '<br />';
echo $this->email->print_debugger();

exit;
```
