### ISSUE TITLE
Why check for mailer_engine?

### ISSUE THREAD

**Issue by Synchro** [ivantcholakov/codeigniter-phpmailer#4]
Throughout your library code you have many checks for `mailer_engine` like this:

```php
if ($this->mailer_engine == 'phpmailer') {
```

Surely it's implicit in the fact that you're using this class that this will always be true, so all these checks are unnecessary?

I see there is a provision to use a different value in the constructor, but if that is the case, why would this class even be instantiated? If you want to use `codeigniter` as the `mailer_engine`, you'd just instantiate `CI_Email` and not `MY_Email`. If anything it looks like you're working around an upstream bug or limitation in CI - is that the case?

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-phpmailer/blob/master/config/email.php#L3

I am supporting a possibility for switching between the CodeIgniter's Email library and PHPMailer. And I use it for testing purposes, for comparison what and how is supported by the two solutions.

**Comment by Synchro** [comment]
I get that (it's what drives the switcher in the constructor), but why wouldn't you do this further upstream, when creating your instance:

```php
if (isset($config['useragent'])) {

	$useragent = trim($config['useragent']);
	$mailer_engine = strtolower($useragent);

	if (strpos($mailer_engine, 'phpmailer') !== false) {
		$mailer = new MY_Email;
	} elseif(strpos($mailer_engine, 'codeigniter') !== false) {
		$mailer = new CI_Email;
	} else {
		unset($config['useragent']);    // An invalid setting;
	}
}
```

otherwise it seems to defeat much of the point of having it as a subclass - why have a subclass be able to emulate its parent when you could get a guaranteed-accurate implementation by using the parent class directly? The conventional approach would be to use a factory pattern to create the appropriate class for you, or allow you to inject an instance.

**Comment by ivantcholakov** [comment]
I got your point, it is reasonable and I will have it in mind for a future improvement.

At the moment the custom library is a wrapper to the original CodeIgniter Email library. Between CodeIgniter 2 and CodeIgniter 3 there are slight changes in the API and the wrapper deals with them. With this custom library and enable PHPMailer engine a developer may use the full power even on CodeIgniter 2.

Anyway, your suggestion would make code cleaner, I will try to find time for this improvement.

Currently my plan is just waiting you to make your next release, then I will make an upgrade-release, and then I will start thinking how to refactor the custom library.

**Comment by ivantcholakov** [comment]
Let this issue stay open.

**Comment by Synchro** [comment]
That makes more sense - I'm not a CI user. I think the wrapper should be split into its own class, then extend that for PHPMailer so instead of:

```php
class MY_Email extends CI_Email...
```
have

```php
class Wrapper_Email extends CI_Email {
//Wrapper stuff happens here
}
class MY_Email extends Wrapper_Email {
//PHPMailer stuff happens here
}
```

then maybe make an additional class that deals with choosing the implementation according to the config.

I'm not sure when I'll do the next PHPMailer release - there are a few nice things that have not been released yet (particularly EHLO parsing), but nothing major.

**Comment by ivantcholakov** [comment]
I figured out a possible way how it could be reworked. Conditions: PHP 5.2.4 (no traits), supporting CI 2.x and CI 3.x.

file MY_Email.php:
```php
// A fragment for getting the configuration option $mailer_engine
...
//

switch ($mailer_engine) {
    case 'phpmailer'
        require_once dirname(__FILE__).'/MY_Phpmailer_Email.php';
        break;
    default:
        require_once dirname(__FILE__).'/MY_Codeigniter_Email.php';
        break;
}
```

file MY_Phpmailer_Email.php
```php
require_once dirname(__FILE__).'/MY_Base_Email.php';
class MY_Email extends MY_Base_Email {
// Code using PHPMailer
}
```

file MY_Codeigniter_Email.php
```php
require_once dirname(__FILE__).'/MY_Base_Email.php';
class MY_Email extends MY_Base_Email {
// Code using the original library
}
```

file MY_Base_email.php
```php
class MY_Base_Email extends CI_Email{
// Common additional methods (html -> plain text, etc.)
}
```

It is possible, but I think doing this just for the sake of removing several mailer_engine checks is not worth-while. I prefer to keep code within one file only because I don't want to make expired the article http://bisakomputer.com/membuat-pengiriman-email-terjadwal-dengan-framework-codeigniter/

I prefer the current slightly hackish way, it works well since a long time.

It would be better in its future versions CodeIgniter to provide an official interface for switching between mailer engines.

**Comment by Quix0r** [comment]
On one side you have `useragent`, on the other side you have `mailer_engine` ? A little bit unintuional, that `useragent` is the "switch" for choosen the right mailer agent.

And I more vote for that CI has built-in support for one mailer engine only.

Just my 2 cents.

**Comment by ivantcholakov** [comment]
@Quix0r

1
'useragent' is a configuration option. I did not want in the past to introduce a new configuration option and this is a harmless decision that I am not going to change.

$this->mailer_engine is a **protected property**, for internal usage. Please, give me the right to do such things. :-)

2
Yes, CI has its own CI_Email library, if you are happy about using it - fine.
