### ISSUE TITLE
Use of undefined constant VENDORPATH

### ISSUE THREAD

**Issue by AEWhiteDevs** [ivantcholakov/codeigniter-phpmailer#40]
A PHP Error was encountered
Severity: Warning

Message: Use of undefined constant VENDORPATH - assumed 'VENDORPATH' (this will throw an Error in a future version of PHP)

Filename: helpers/MY_email_helper.php

Line Number: 13

Backtrace:

File: C:\xampp7.3.7\htdocs\s3\S3\application\helpers\MY_email_helper.php
Line: 13
Function: _error_handler

File: C:\xampp7.3.7\htdocs\s3\S3\application\controllers\Txts.php
Line: 6
Function: __construct

File: C:\xampp7.3.7\htdocs\s3\S3\index.php
Line: 315
Function: require_once

**Comment by ivantcholakov** [comment]
The constant has to be created by you once, have a look at README.md on how to do it.
