### ISSUE TITLE
Renaming attached file not working.

### ISSUE THREAD

**Issue by scripterTW** [ivantcholakov/codeigniter-phpmailer#7]
Hi, I'm trying to renaming attached file, but it's not working.

in MY_Email.php
at line 507:   
```php
$newname = basename($file); 
```
it works if I changed to:
```php
$newname = basename($newname); 
```

Thanks

**Comment by ivantcholakov** [comment]
I confirm that this part of code looks strange, it is my mistake. I am preparing a update.

**Comment by ivantcholakov** [comment]
Update to RELEASE 1.1.8.
