### ISSUE TITLE
{unwrap} left in email

### ISSUE THREAD

**Issue by milkboyuk** [ivantcholakov/codeigniter-phpmailer#8]
Had the codeigniter {unwrap} & {/unwrap} tags in my emails. They did not get removed. I could not find any phpmailer equivalent. The easiest solution (apart from not using them, which was not an option for me) was to just remove them by amending line 305 from: 
           $this->phpmailer->Subject = (string) $subject;
to:
           $this->phpmailer->Subject = str_replace(array('{unwrap}', '{/unwrap}'), '', (string) $subject); 

And line 321 from:
            $this->phpmailer->Body = $body;
to:
            $this->phpmailer->Body = str_replace(array('{unwrap}', '{/unwrap}'), '', $body);

This is for CI 2. Not sure how it applies to to CI 3.

**Comment by ivantcholakov** [comment]
As far as I can see, the situation for CI3 would be the same. And PHPMailer's method is different.
I agree with your solution and will test and implement it for the next release. Let this task stay open.

**Comment by milkboyuk** [comment]
Also thank you for this. You saved me hours of pain and stress today. So thank you.

**Comment by ivantcholakov** [comment]
@milkboyuk Why do you need to clean the subject?

**Comment by ivantcholakov** [comment]
@milkboyuk

I think that subject does not need filtering the {unwrap} and {/unwrap}, anyway I did it because you asked so. RELEASE 1.1.12.
