### ISSUE TITLE
errors in hosting

### ISSUE THREAD

**Issue by sidaurukfreddy** [ivantcholakov/codeigniter-phpmailer#9]
hi dear, 
why this give me errors like this already configuration same like yours
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by ivantcholakov** [comment]
Could you post your configuration, I can have a brief look at it.

**Comment by elca2712** [comment]
Hi,

Sorry If I use your issue but I have the same problem in hosting.

I tried today to use codeigniter-phpmailer,it's work fine in localhost but in hosting I have a timeout (110)

This is my email configuration:
$config['useragent']        = 'PHPMailer';             
$config['protocol']         = 'smtp';                   
$config['mailpath']         = '/usr/sbin/sendmail';
$config['smtp_host']        = 'host';
$config['smtp_user']        = 'user';
$config['smtp_pass']        = 'pwd';
$config['smtp_port']        = 587;
$config['smtp_timeout']     = 5;                      
$config['smtp_crypto']      = 'tls';                    
$config['smtp_debug']       = 4;                      
$config['wordwrap']         = true;
$config['wrapchars']        = 76;
$config['mailtype']         = 'html';                   
$config['charset']          = null;                     
$config['validate']         = true;
$config['priority']         = 3;                       
$config['crlf']             = "\n";                   
$config['newline']          = "\n";                    
$config['bcc_batch_mode']   = false;
$config['bcc_batch_size']   = 200;
$config['encoding']         = '8bit';

**Comment by ivantcholakov** [comment]
1. Check https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host

2. On your hosting server you may run a script like this http://stackoverflow.com/a/19260241 (change the parameters) so you can see whether a connection can be established.

**Comment by sidaurukfreddy** [comment]
where is this script should be run, combine in controller or what ? please expalain more la, thanks

$host = "smtp.gmail.com";
$port = "587";
$checkconn = fsockopen($host, $port, $errno, $errstr, 5);
if(!$checkconn){
        echo "($errno) $errstr";
 } else {
        echo 'ok';
  }

**Comment by ivantcholakov** [comment]
@sidaurukfreddy

Create somewhere in your computer a new file named test_email_host.php
Then, copy the following source code (the whole text in grey) and paste it within the file test_email_host.php

```php
<?php

// File: test_email_host.php

// Testing connection to a SMTP host from a web server.

// See http://stackoverflow.com/a/19260241
// See https://github.com/ivantcholakov/codeigniter-phpmailer/issues/9
// See also https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host

// Note: If you use Gmail, allow IMAP access (as I remember) to your account there.

// Upload this file to the DOCUMENT_ROOT directory of your web server.
// Then open a browser and open the link http://your-web-server.com/test_email_host.php
// and see the result.
// After testing remove this file from your web server.

$host = 'smtp.gmail.com';   // Change this accordingly.
$port = '587';              // Change this accordingly.

//------------------------------------------------------------------------------

$errno = null;
$errstr = null;

$checkconn = fsockopen($host, $port, $errno, $errstr, 5);

if (!$checkconn) {
    echo "($errno) $errstr";
} else {
    echo 'ok';
}
```

Within the file modify the variables $host and $port, set your values. Save it.

Read the comments within the file about what to do next.

**Comment by sidaurukfreddy** [comment]
oke thanks for respond wait minute what this means 

//After testing remove this file from your web server

Thanks a lot will tested later on after fixed the bugs

**Comment by ivantcholakov** [comment]
@sidaurukfreddy
After testing, when your mailer gets working, delete the file test_email_host.php from your web server. The file is temporary, for testing purpose only.
